spring:
  mail:
    host: smtp.163.com
    username: 13127712613@163.com
    password: 686933hcy
    properties:
        mail:
            smtp:
                auth: true
                timeout: 25000